### ISSUE TITLE
Getting Error on using cordova-sms-plugin while creating ipa on phonegap build 

### ISSUE THREAD

**Issue by neha9831** [cordova-sms/cordova-sms-plugin#98]
I have looked towards all the solutions provided on github related to sms plugin but i am not able to find the suitable solution for my problem. When I am creating the ipa file with sms plugin I am getting the following mentioned error.;-
![ioserror](https://cloud.githubusercontent.com/assets/12149468/17922730/369fe044-69fe-11e6-9c77-ccfce3c79018.PNG)
I am using the latest version of  PhoneGap (iOS / Android / Windows) cli-6.3.0 (4.2.0 / 5.2.1 / 4.4.1) and also the latest version of the sms plugin that is version 0.1.2.  Please help me to find the exact solution.

**Comment by dbaq** [comment]
Hey @neha9831,

I am going to need more that just a UI error message. Can you paste the logs please.

**Comment by agarrharr** [comment]
@neha9831 Where is that screenshot from? What program are you using to build the app? Have you tried using the cordova cli?

**Comment by neha9831** [comment]
Thanks For your reply dbaq . I am sending complete log as attachment pls check
[log.txt](https://github.com/cordova-sms/cordova-sms-plugin/files/436490/log.txt)

Hey this screen shot is from PhoneGap Build. I am using PhoneGap Build To build the app. And I Am using PhoneGap Desktop Version not CLI

**Comment by dbaq** [comment]
Here is the important stacktrace:

```
/project/ExamHalls/Plugins/com.cordova.plugins.sms/Sms.m:2:9: fatal error: 'Cordova/NSArray+Comparisons.h' file not found
#import <Cordova/NSArray+Comparisons.h>
```

it looks like it is related to the latest version of phonegap build.

see 
- https://github.com/litehelpers/Cordova-sqlite-storage/issues/228
- https://github.com/j3k0/cordova-plugin-purchase/issues/246

@neha9831, can you try to uninstall and reinstall the plugin please?

thank you

**Comment by neha9831** [comment]
Thanks For your reply,, as per your suggestion I have uninstalled and then installed the plugin, But still same error found

**Comment by dbaq** [comment]
hey @neha9831, have you figured this out? I googled it but was not able to find any serious hint.

**Comment by neha9831** [comment]
Hello @dbaq No, My problem is not figured out I am still getting same error. Same here I also googled for the issue but not able to find the appropriate solution for SMS Plugin

**Comment by ikennah** [comment]
I am having the same issue, and this version is not compatible with the latest Cordova cli-6.3.0 version.

**Comment by vitaly87** [comment]
What version should I use?

**Comment by ikennah** [comment]
Version 5 works. Not sure if we can get it update to latest version

**Comment by dbaq** [comment]
hey @ikennah,

I just tried it and it works fine with cordova cli 6.3.1. 

Here is what I did:

```
$ cordova create helloCordovaTestCdv6.3.1
$ cd helloCordovaTestCdv6.3.1
$ cordova plugin add cordova-sms-plugin
$ cd www
$ cordova platform add android
$ cordova build android
$ ll
$ nano index.html
$ nano js/index.js
$ cd ..
$ cordova run android
```

```
$ cordova -v
6.3.1
```

```
$ cordova platform
Installed platforms:
  android 5.2.2
```

This issue is phonegap related not cordova. If you are having difficulties please open another issue.

**Comment by dbaq** [comment]
Closing this one since no answer.
